### ISSUE TITLE
pip install fails to find a version to install

### ISSUE THREAD

**Issue by lixxu** [jaraco/path.py#114]
Py version should not be specified as it's available for py2&3. 
It causes below pip install error:
```
$ pip install path.py
Collecting path.py
  Could not find a version that satisfies the requirement path.py (from versions: )
No matching distribution found for path.py
```

![pathpy_bug](https://cloud.githubusercontent.com/assets/264487/15643399/be38d064-267f-11e6-8df8-895a84bdee3a.png)

**Comment by jaraco** [comment]
It's not an issue with the package name either. I'm unable to replicate the issue.

```
$ python2.7 -m pip --version
pip 8.1.2 from /Library/Python/2.7/site-packages (python 2.7)
$ python2.7 -m pip install -vvv --user --no-cache path.py
Collecting path.py
  1 location(s) to search for versions of path.py:
  * https://pypi.python.org/simple/path-py/
  Getting page https://pypi.python.org/simple/path-py/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/path-py/ HTTP/1.1" 200 3915
  Analyzing links from page https://pypi.python.org/simple/path-py/
    Found link https://pypi.python.org/packages/01/9c/042dad431173df683121fea53d055b83b811504864d6ecfdd32dcfbb2d7c/path.py-3.0.1.zip#md5=12dc60ddc03360d4f1b05b1a3a6f02bf (from https://pypi.python.org/simple/path-py/), version: 3.0.1
    Found link https://pypi.python.org/packages/02/cc/a90b8030ea6ae79e0fa91ecb240e5ce7870b55d03e4bc1f60b411059de21/path.py-6.0.zip#md5=46692a75b032f4cc9c7539c11256a95d (from https://pypi.python.org/simple/path-py/), version: 6.0
    Found link https://pypi.python.org/packages/0b/57/12aafdd4616ff7fcac744e77080b3165d2f3d8509868bbaac77368021ed5/path.py-7.7.1.tar.gz#md5=3f0d717e82aa2270bbda8e7bf36ead43 (from https://pypi.python.org/simple/path-py/), version: 7.7.1
    Found link https://pypi.python.org/packages/11/96/77017f49e8ef51e7a82a31b7daa57266975e02fd3ee922e18a5b0803ff74/path.py-7.7.1-py2.py3-none-any.whl#md5=36a708e73f4b11a0eec55ad2ba946385 (from https://pypi.python.org/simple/path-py/), version: 7.7.1
    Found link https://pypi.python.org/packages/1d/c5/c53bac9c3ea9317a03bd6830fef0544760832e34fe49a17acce738bdde53/path.py-3.0.zip#md5=97f6941cd53722c508d959ecc398dc3c (from https://pypi.python.org/simple/path-py/), version: 3.0
    Found link https://pypi.python.org/packages/26/01/24b69353a7260052cf1592f94991cf56b58b3f72687df6cfb54ff1e1b165/path.py-5.2.zip#md5=96fe002b1797b221c269ff2ed1fdbc28 (from https://pypi.python.org/simple/path-py/), version: 5.2
    Found link https://pypi.python.org/packages/2f/ec/34a818f18b298abc245e8bc8c1748f026491509c895f51a7779f0d7f57e6/path.py-2.3.zip#md5=6cb6bdcdfd70443bd1dfa55d46c587c2 (from https://pypi.python.org/simple/path-py/), version: 2.3
    Found link https://pypi.python.org/packages/3d/ce/5fe33c37cc95f853271444daba3eb499698b6a19d7b83068ad1339ed1b8b/path.py-7.2.zip#md5=e0c54b25e2199c3bb325520d9f9d047a (from https://pypi.python.org/simple/path-py/), version: 7.2
    Found link https://pypi.python.org/packages/3e/41/5e6f3286769274f287cc70c220cd73b5debb6876e213892e65d4be3bb6ef/path.py-7.6-py2.py3-none-any.whl#md5=19e868f197c5f388b0d114bb77a7f9dd (from https://pypi.python.org/simple/path-py/), version: 7.6
    Found link https://pypi.python.org/packages/44/a1/58d8c516dc63299222ef2e14f00be958de48ea0088d9ea9943c15743a776/path.py-7.5-py2.py3-none-any.whl#md5=8b6de5fcca3b749410adc74ec471db8e (from https://pypi.python.org/simple/path-py/), version: 7.5
    Found link https://pypi.python.org/packages/48/51/fe62dfeeb3b8f1b24796f687214137a63b0449170c6ea183bcc6db12cdd9/path.py-7.6.2.tar.gz#md5=926e85fe170e8207d109196216399559 (from https://pypi.python.org/simple/path-py/), version: 7.6.2
    Found link https://pypi.python.org/packages/48/69/7b043fedb6475d35c88bb08e2330c16df4a8902d7f899ffd7eca0ae033cd/path.py-2.4.zip#md5=9ad267b00de6421fcedaacc8854ae762 (from https://pypi.python.org/simple/path-py/), version: 2.4
    Found link https://pypi.python.org/packages/48/f0/e8a537dd3998f7c05a66ad3217778f0cf89dd91757ecdb53a33d4989a7db/path.py-5.3.zip#md5=dd3b169dfb76a2711094beb861705bc9 (from https://pypi.python.org/simple/path-py/), version: 5.3
    Found link https://pypi.python.org/packages/55/c2/ebb3dfbd1b8575fe7dd451338e87bb96dbe480c278f53a09c8f1ad7717d1/path.py-2.2.2.tar.gz#md5=3a3262b9049d294ddbd6f7453d45e699 (from https://pypi.python.org/simple/path-py/), version: 2.2.2
    Found link https://pypi.python.org/packages/5b/f6/602ae264f254509a30c6572e7d5fddd6b7fce10aaa40c1bda2f4f8d1e0f4/path.py-8.1-py2.py3-none-any.whl#md5=d515df778872fa9386e100f4945b97d2 (from https://pypi.python.org/simple/path-py/), version: 8.1
    Found link https://pypi.python.org/packages/64/ca/1ad13d3f5cc0ca831e8840e5f01d4b2e5f6f5104166c4bd3025596500c13/path.py-7.7-py2.py3-none-any.whl#md5=d8d47226f6ae65d6380384762c0df210 (from https://pypi.python.org/simple/path-py/), version: 7.7
    Found link https://pypi.python.org/packages/69/1d/e7a4a6aae83cd6e3457b57f0e4110d7753be17a5da61e08983a90cdec580/path.py-2.4.1.zip#md5=ffdb1d4ce258af95de589b41f6e5b8af (from https://pypi.python.org/simple/path-py/), version: 2.4.1
    Found link https://pypi.python.org/packages/6c/7a/a4d231350a371fad2cfc2d59ca4cb292c7ded34c9404280000aabe82cda3/path.py-7.1.zip#md5=70d430fbe408dd313cf0effcb79a294d (from https://pypi.python.org/simple/path-py/), version: 7.1
    Found link https://pypi.python.org/packages/7a/b2/0e37cf4037cd7b5574b7e3e53660e93da1f5d3c977cdacf836fb0a0b5dfe/path.py-4.4.zip#md5=09a9e903996fd78c5b67172f44a0e301 (from https://pypi.python.org/simple/path-py/), version: 4.4
    Found link https://pypi.python.org/packages/82/80/02de92bc25224a64837c3ef6d2dfda846d26a3fc0181817afc7121e33c35/path.py-4.0.zip#md5=5c191541a5682b0fd5e850d5c554b5d6 (from https://pypi.python.org/simple/path-py/), version: 4.0
    Found link https://pypi.python.org/packages/85/30/fed95a0f4fe785256fe15c85eafc53907e728c75e252f9a947f32d0478e5/path.py-7.0.zip#md5=ac9dad50af974237d1937f9b16c2959a (from https://pypi.python.org/simple/path-py/), version: 7.0
    Found link https://pypi.python.org/packages/85/80/d13c3e5058c14f0bf3c19e9596a70f1e805fcda8510531f338b9e96cc5c7/path.py-8.2.1.tar.gz#md5=7334796c9ed6036cb89bcd30d8409f91 (from https://pypi.python.org/simple/path-py/), version: 8.2.1
    Found link https://pypi.python.org/packages/86/20/ff3d05001f08f06a0d8602265445b47427862481549772ce1fcb2947b650/path.py-2.6.zip#md5=11824d2662b89aaed42974e5076495bf (from https://pypi.python.org/simple/path-py/), version: 2.6
    Found link https://pypi.python.org/packages/8b/47/8395b1995fec8aa87d665154d9c44866dffe4db6de0e3710ecfc7d078ddc/path.py-7.6.1-py2.py3-none-any.whl#md5=9ecb0f3671bd637f7282c01c3b274d7d (from https://pypi.python.org/simple/path-py/), version: 7.6.1
    Found link https://pypi.python.org/packages/90/75/0116e612c9ae89d32cf908fd3794f6b7bd11b95304e8aa5da0a6e66698ec/path.py-3.1.zip#md5=02afda308625f47b081725140dc52e7e (from https://pypi.python.org/simple/path-py/), version: 3.1
    Found link https://pypi.python.org/packages/90/bb/3440e0734cb2dcfbf3644546dad7dfc08b197d5dd52877de95f95fd459b2/path.py-8.1.2.tar.gz#md5=31d07ac861284f8148a9041064852371 (from https://pypi.python.org/simple/path-py/), version: 8.1.2
    Found link https://pypi.python.org/packages/93/aa/d35051aea089d7cb51beba319df516ce0a6d0d7a768deb975b063e74ab53/path.py-5.0.zip#md5=c6e111ecb3e78b3056133e1f7cd45ffb (from https://pypi.python.org/simple/path-py/), version: 5.0
    Found link https://pypi.python.org/packages/a0/b1/b59dea38df0b4082d7358b105a2205d006f4b793aef175c5a2319f9d90b1/path.py-2.6.1.zip#md5=2741c24dae273ee04c6223401a426450 (from https://pypi.python.org/simple/path-py/), version: 2.6.1
    Skipping link https://pypi.python.org/packages/a5/94/0a4b349d66c62a9e72e2132c428a82fcb8b99eaeee27ff9fa1975bbafd67/path-2.2.zip#md5=941660081788282887f652510d80e64e (from https://pypi.python.org/simple/path-py/); wrong project name (not path.py)
    Found link https://pypi.python.org/packages/a8/de/94ba9c6d2cca9307c762492def8105803044571bd09a4a36aa2c648fe2bf/path.py-8.2-py2.py3-none-any.whl#md5=85d5c3dd6ab05f26ade8e6e1339599a3 (from https://pypi.python.org/simple/path-py/), version: 8.2
    Found link https://pypi.python.org/packages/ac/c8/b78ccd6d362bf58ddef1a0b6af062264b44b06b6bd65261768e43c947aa2/path.py-8.1.1.tar.gz#md5=40a8cba213479bfd053a5aae0b801562 (from https://pypi.python.org/simple/path-py/), version: 8.1.1
    Found link https://pypi.python.org/packages/b1/a8/86cf4ecb47fc54c92420b2bb9f5fbe3206f44579ecfb42bcb7f40d35d6ec/path.py-4.1.zip#md5=7427723005047d51237b8923cebe9030 (from https://pypi.python.org/simple/path-py/), version: 4.1
    Found link https://pypi.python.org/packages/b9/43/e33a5e57b61e79adb7ea22716fef87e72da4b39367dafd89fcb2e2aa1b5f/path.py-3.2.zip#md5=557152b820705cd561ff54250e273459 (from https://pypi.python.org/simple/path-py/), version: 3.2
    Found link https://pypi.python.org/packages/c0/13/5920018cdbae45405e480c9c69228735f5da4627fe57a5b209f8e77ec2a4/path.py-7.6.2-py2.py3-none-any.whl#md5=1a1a3f0bac54aa2be34ca4a83c683196 (from https://pypi.python.org/simple/path-py/), version: 7.6.2
    Found link https://pypi.python.org/packages/c0/7e/2cc778a5f0925342f842f50c0c2f258c804b241a206f70ae687f618b7d88/path.py-7.4.tar.gz#md5=451f2c82d23330290a1228cd352b4796 (from https://pypi.python.org/simple/path-py/), version: 7.4
    Found link https://pypi.python.org/packages/c6/32/43e1c759aef61d33c1a72831cad07095b7a567c034dafe6d4deecfc0b90d/path.py-8.1.tar.gz#md5=6203f1e1dd221404f28d612a90104a9c (from https://pypi.python.org/simple/path-py/), version: 8.1
    Found link https://pypi.python.org/packages/ca/9d/920a8c6def879091cbdc0f694270454df60272e938134891d4a7fa3e8d9b/path.py-4.3.zip#md5=f0583bdcf6e19516e7387eeca6526abb (from https://pypi.python.org/simple/path-py/), version: 4.3
    Found link https://pypi.python.org/packages/ca/ac/dcb630927536d7dad3fc4c1fd709f80085a65d6bd6810de1e2b0f24f7db6/path.py-4.2.zip#md5=c64427ca936e23fef1665695fdf6f6bd (from https://pypi.python.org/simple/path-py/), version: 4.2
    Found link https://pypi.python.org/packages/cc/2c/969f346ac0fdf1a5cecb746362f750c08f5c03258b1ed3ae5f31d776946a/path.py-8.1.2-py2.py3-none-any.whl#md5=1fd492da6f99cd027c561382498df71b (from https://pypi.python.org/simple/path-py/), version: 8.1.2
    Found link https://pypi.python.org/packages/cf/f7/960897ceb043298ac4b22b8c3dc643a16666f176d4f85a5e5351d185be6c/path.py-5.1.zip#md5=67c0e1b8c1b1b889ea77aef5224ccc29 (from https://pypi.python.org/simple/path-py/), version: 5.1
    Found link https://pypi.python.org/packages/d0/2f/65d17ddb9b2611a36c73bd965ee6895d7db6208e1b0ba97285294aac367a/path.py-6.2.zip#md5=95e0a9317f836da2d30dc602b2d53248 (from https://pypi.python.org/simple/path-py/), version: 6.2
    Found link https://pypi.python.org/packages/d7/09/81ab9232fdc5ba69b074ae07906dcc4b1c35a8e54f4bfeffc52e2469931b/path.py-7.4-py2.py3-none-any.whl#md5=b7837dfb9b8ee3763ce3a50004199f39 (from https://pypi.python.org/simple/path-py/), version: 7.4
    Found link https://pypi.python.org/packages/d7/65/7e564226c7b6108b9e89a33d2509391e15adacff84ee1a96fa2b0b792c3a/path.py-2.5.zip#md5=6fc8454efb2e74357ccb2d08eb772832 (from https://pypi.python.org/simple/path-py/), version: 2.5
    Found link https://pypi.python.org/packages/dd/f6/b45950e3a8b05c7ce7b551a02b20a042031a5574b732e89d5e5e0add4856/path.py-7.6.1.tar.gz#md5=a759fa583781ef94e959c0823075d586 (from https://pypi.python.org/simple/path-py/), version: 7.6.1
    Found link https://pypi.python.org/packages/e2/33/cfd0ec47430cf88486bdb5fc690d90ce9c431f7576badf4ce1165c2cfe2a/path.py-7.5.tar.gz#md5=e3c906a1a9e281bdf018574d3a229ae0 (from https://pypi.python.org/simple/path-py/), version: 7.5
    Found link https://pypi.python.org/packages/e8/b4/3defecce7730bf34531e088134e93f7b4b4396189cc38e93cebb593de1bc/path.py-7.3.zip#md5=9fc7ba8cd4ec90797154d1f5a4380078 (from https://pypi.python.org/simple/path-py/), version: 7.3
    Found link https://pypi.python.org/packages/f3/cc/e813ac7b15c2c12b91c1ed38563c43d2c42d9d0858f9fa78d13b77b96e3a/path.py-7.7.tar.gz#md5=61cfd1a7d0409bbab13f2dc236d2c7ab (from https://pypi.python.org/simple/path-py/), version: 7.7
    Found link https://pypi.python.org/packages/f5/0c/71599fdf5e2baa6e71b692bc8a9d7213ba273f336638da777d812dee788d/path.py-6.1.zip#md5=b79ddd10e5246b5a343b582e8a157983 (from https://pypi.python.org/simple/path-py/), version: 6.1
    Found link https://pypi.python.org/packages/f5/7a/571065af1ad0211ce9214d34ba540fa0ba6bc5caaf6b2698f23203dc681c/path.py-8.1.1-py2.py3-none-any.whl#md5=4bc7732859933fc2cad2712fdd29597e (from https://pypi.python.org/simple/path-py/), version: 8.1.1
    Found link https://pypi.python.org/packages/f6/f7/ab0aed55dbe6e26a2ca120333a518edfd9041c810404a1de42c3374e4383/path.py-7.6.tar.gz#md5=e70090139fc136462d52460b0e4a00d1 (from https://pypi.python.org/simple/path-py/), version: 7.6
    Found link https://pypi.python.org/packages/fb/50/80064e8494c4ad29de4d05659feaa6b09aced67982ad16ab736662e94e30/path.py-7.3-py2.py3-none-any.whl#md5=c7b9ef85d52b630020d5eb083b77c56d (from https://pypi.python.org/simple/path-py/), version: 7.3
    Found link https://pypi.python.org/packages/fc/fc/dcae2146aed6becbea77158eddb4e437718170efeade0f7fdf0aebe46b94/path.py-8.2.1-py2.py3-none-any.whl#md5=f04e58a16a3be2eea1a8d0bbcec6beb8 (from https://pypi.python.org/simple/path-py/), version: 8.2.1
    Found link https://pypi.python.org/packages/ff/0c/0959e74ce1f9b317ce442343ec0074050ab219dd89e55fa13f97df6ebc65/path.py-8.2.tar.gz#md5=750cf1ea7a257cfa76ed41096912cf79 (from https://pypi.python.org/simple/path-py/), version: 8.2
  Using version 8.2.1 (newest of versions: 2.2.2, 2.3, 2.4, 2.4.1, 2.5, 2.6, 2.6.1, 3.0, 3.0.1, 3.1, 3.2, 4.0, 4.1, 4.2, 4.3, 4.4, 5.0, 5.1, 5.2, 5.3, 6.0, 6.1, 6.2, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.6.1, 7.6.2, 7.7, 7.7.1, 8.1, 8.1.1, 8.1.2, 8.2, 8.2.1)
  "GET /packages/fc/fc/dcae2146aed6becbea77158eddb4e437718170efeade0f7fdf0aebe46b94/path.py-8.2.1-py2.py3-none-any.whl HTTP/1.1" 200 28154
  Downloading path.py-8.2.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/fc/fc/dcae2146aed6becbea77158eddb4e437718170efeade0f7fdf0aebe46b94/path.py-8.2.1-py2.py3-none-any.whl#md5=f04e58a16a3be2eea1a8d0bbcec6beb8 (from https://pypi.python.org/simple/path-py/)
Installing collected packages: path.py

Successfully installed path.py-8.2.1
Cleaning up...
```

Can you run the command with `-vvv` and see if that reveals the underlying failure?

**Comment by lixxu** [comment]
Sorry, you're right. It's not a true issue. It's because my pypi mirror issue.
aliyun can only use `http://mirrors.aliyun.com/pypi/simple/path.py` to find the package while official pypi can use both. Maybe it's the mirror sync issue.
```
λ pip install -vvv --user --no-cache path.py
Collecting path.py
  1 location(s) to search for versions of path.py:
  * http://mirrors.aliyun.com/pypi/simple/path-py/
  Getting page http://mirrors.aliyun.com/pypi/simple/path-py/
  Starting new HTTP connection (1): mirrors.aliyun.com
  "GET /pypi/simple/path-py/ HTTP/1.1" 404 None
  Could not fetch URL http://mirrors.aliyun.com/pypi/simple/path-py/: 404 Client Error: Not Found for url: http://mirrors.aliyun.com/pypi/simple/path-py/ - skipping
  Could not find a version that satisfies the requirement path.py (from versions: )
Cleaning up...
No matching distribution found for path.py
Exception information:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 522, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 268, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\python27\lib\site-packages\pip\index.py", line 491, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for path.py
```

**Comment by jaraco** [comment]
See pypa/pip#3672 and pypa/pip#3666 for more details. Short term workaround is to downgrade to pip 8.1.1.

**Comment by lixxu** [comment]
Thanks, I switched to `https://pypi.doubanio.com/simple/` that solved the problem. :)

**Comment by Deepakchawla** [comment]
I am getting the same error while installing with pip command...

`(dchawla-env) D:\School Project v2\ws-py-dchawla\my-class-api>pip install pip install django
Requirement already satisfied: pip in d:\schoolvirtualev\dchawla-env\lib\site-packages
Collecting install
  Could not find a version that satisfies the requirement install (from versions: )
No matching distribution found for install`

I am using windows 7 and IntelliJ IDEA 2017.1 x64...

**Comment by jaraco** [comment]
Hi @deepakchawla. Your issue is you typed 'pip install' twice, so pip tried to install "pip", "install", and then Django, but failed to find "install". 

This package where you've reported the issue is path.py and is unrelated. You may want to start with sites like StackOverflow for questions as you familiarize yourself with Python. Good luck!

**Comment by RaynerHM** [comment]
Me presentaba el mismo problema al tratar de instalar Django en Windows.

La solución fue, abrir la Consola como **Administrador**. Y eso me funcionó.

Saludos.

**Comment by Mohammed-Toufiq** [comment]
Hi, I am getting the following error while running as mentioned below. Please help me resolve this.

sh run.sh
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
Initializing config/shed_tool_conf.xml from shed_tool_conf.xml.sample
Initializing config/shed_tool_data_table_conf.xml from shed_tool_data_table_conf.xml.sample
Initializing config/shed_data_manager_conf.xml from shed_data_manager_conf.xml.sample
Initializing tool-data/shared/ucsc/builds.txt from builds.txt.sample
Initializing tool-data/shared/ucsc/manual_builds.txt from manual_builds.txt.sample
Initializing static/welcome.html from welcome.html.sample
Creating Python virtual environment for Galaxy: .venv
To avoid this, use the --no-create-venv flag or set $GALAXY_VIRTUAL_ENV to an
existing environment before starting Galaxy.
Fetching https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   122    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   281  100   281    0     0    193      0  0:00:01  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 1679k  100 1679k    0     0   496k      0  0:00:03  0:00:03 --:--:-- 1582k
Verifying /var/folders/xm/rm683mz11pscdh0wwh4z9xdc0000gn/T/galaxy-virtualenv-XXXXXX.OEVHTSyh/virtualenv-13.1.2.tar.gz checksum is aabc8ef18cddbd8a2a9c7f92bc43e2fea54b1147330d65db920ef3ce9812e3dc
New python executable in .venv/bin/python
Installing setuptools, pip, wheel...done.
Activating virtualenv at .venv
Collecting pip>=8.1
  Could not find a version that satisfies the requirement pip>=8.1 (from versions: )
No matching distribution found for pip>=8.1
